// Locations
export const LOADING_LOCATIONS = 'LOADING_LOCATIONS';
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS';
export const FETCH_LOCATIONS_FAILURE = 'FETCH_LOCATIONS_FAILURE';
export const LOADING_MAP_API = 'LOADING_MAP_API';
export const CLEAR_LOCATIONS = 'CLEAR_LOCATIONS';
export const ALL_LOCATIONS_SUCCESS = 'ALL_LOCATIONS_SUCCESS';

// Maps
export const FETCH_MAP_API_SUCCESS = 'FETCH_MAP_API_SUCCESS';
export const FETCH_MAP_API_FAILURE = 'FETCH_MAP_API_FAILURE';

// Single location actions type
export const LOADING_SINGLE_LOCATION = 'LOADING_SINGLE_LOCATION';
export const FETCH_SINGLE_LOCATIONS_SUCCESS = 'FETCH_SINGLE_LOCATIONS_SUCCESS';
export const FETCH_SINGLE_LOCATIONS_FAILURE = 'FETCH_SINGLE_LOCATIONS_FAILURE';

// activeLocation types
export const SET_ACTIVE = 'SET_ACTIVE';
export const CLEAR_ACTIVE = 'CLEAR_ACTIVE';

// Geolocation
export const SET_GEOLOCATION_TRUE = 'SET_GEOLOCATION_TRUE';
export const SET_GEOLOCATION_FALSE = 'SET_GEOLOCATION_FALSE';
export const SET_GEOLOCATION_VALUE = 'SET_GEOLOCATION_VALUE';

// Auth
export const AUTH_LOAD = 'AUTH_LOAD';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE_LOGIN = 'AUTH_FAILURE_LOGIN';
export const AUTH_FAILURE_SIGNUP = 'AUTH_FAILURE_SIGNUP';
export const SET_COOKIE_TO_STATE = 'SET_COOKIE_TO_STATE';

//Email verification
export const VERIFY_EMAIL_LOAD = 'VERIFY_EMAIL_LOAD';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const NEW_VERIFY_EMAIL_SENT = 'NEW_VERIFY_EMAIL_SENT';
export const POPUP_MESSAGE_SEEN = 'POPUP_MESSAGE_SEEN';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';

export const RESET_PASSWORD_LOAD = 'RESET_PASSWORD_LOAD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

// ADD NEW LOCATIONS
export const ADD_NEW_LOCATION_LOAD = 'ADD_NEW_LOCATION_LOAD';
export const ADD_NEW_LOCATION_SUCCESS = 'ADD_NEW_LOCATION_SUCCESS';
export const ADD_NEW_LOCATION_FAIL = 'ADD_NEW_LOCATION_FAIL';
export const CLEAR_NEW_LOCATION = 'CLEAR_NEW_LOCATION';
