// Locations
export const LOADING_LOCATIONS = 'LOADING_LOCATIONS';
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS';
export const FETCH_LOCATIONS_FAILURE = 'FETCH_LOCATIONS_FAILURE';
export const LOADING_MAP_API = 'LOADING_MAP_API';
export const CLEAR_LOCATIONS= "CLEAR_LOCATIONS";

// Maps
export const FETCH_MAP_API_SUCCESS = 'FETCH_MAP_API_SUCCESS';
export const FETCH_MAP_API_FAILURE = 'FETCH_MAP_API_FAILURE';

// Single location actions type
export const LOADING_SINGLE_LOCATION = 'LOADING_SINGLE_LOCATION';
export const FETCH_SINGLE_LOCATIONS_SUCCESS = 'FETCH_SINGLE_LOCATIONS_SUCCESS';
export const FETCH_SINGLE_LOCATIONS_FAILURE = 'FETCH_SINGLE_LOCATIONS_FAILURE';

// activeLocation types
export const SET_ACTIVE = "SET_ACTIVE";
export const CLEAR_ACTIVE = "CLEAR_ACTIVE";

// Geolocation
export const SET_GEOLOCATION_TRUE = "SET_GEOLOCATION_TRUE";
export const SET_GEOLOCATION_FALSE = "SET_GEOLOCATION_FALSE";

// Auth
export const AUTH_LOAD = "AUTH_LOAD";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const RESET_PASSWORD = "RESET_PASSWORD_LOAD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";
