// maps action types
export const LOADING_MAP_API = 'LOADING_MAP_API';
export const FETCH_MAP_API_SUCCESS = 'FETCH_MAP_API_SUCCESS';
export const FETCH_MAP_API_FAILURE = 'FETCH_MAP_API_FAILURE';
export const SET_GEOLOCATION_TRUE = "SET_GEOLOCATION_TRUE";
export const SET_GEOLOCATION_FALSE = "SET_GEOLOCATION_FALSE";

// locations types
export const LOADING_LOCATIONS = 'LOADING_LOCATIONS';
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS';
export const FETCH_LOCATIONS_FAILURE = 'FETCH_LOCATIONS_FAILURE';

// single location actions types
export const LOADING_SINGLE_LOCATION = 'LOADING_SINGLE_LOCATION';
export const FETCH_SINGLE_LOCATIONS_SUCCESS = 'FETCH_SINGLE_LOCATIONS_SUCCESS';
export const FETCH_SINGLE_LOCATIONS_FAILURE = 'FETCH_SINGLE_LOCATIONS_FAILURE';

// activeLocation types
export const SET_ACTIVE = "SET_ACTIVE";
